# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         AxKit-XSP-Sendmail
version:      1.5
version_from: Sendmail.pm
installdirs:  site
requires:
    AxKit:                         1.4
    Email::Valid:                  0
    Mail::Sendmail:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
